name: Release – bump, codegen, publish
on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  DOTNET_VERSION: '8.0.x'

########################################################################
# 1. Version bump
########################################################################
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Tag parsing
      id: ver
      run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

    - name: Patch .csproj
      run: |
        proj=$(git ls-files '*.csproj' | head -n1)
        sed -i -E "s#<Version>[^<]+</Version>#<Version>${{ steps.ver.outputs.version }}</Version>#g" "$proj"

    - name: Create and Merge PR (bump)
      id: bump_pr
      uses: peter-evans/create-pull-request@v7
      with:
        base: master
        commit-message: |
          chore: bump version to ${{ steps.ver.outputs.version }}
        branch: version/${{ steps.ver.outputs.version }}
        delete-branch: true

########################################################################
# 2.1. Codegen - Generate C# and create PR
########################################################################
  codegen-generate:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - run: dotnet tool install GraphQlClientGenerator.Tool --global
    - env:
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
      run: |
        graphql-client-generator \
          --serviceUrl "$GRAPHQL_URL" \
          --outputPath ./src/Poolz.Finance.CSharp.Strapi/StrapiClient.cs \
          --namespace Poolz.Finance.CSharp.Strapi

    - name: Create PR (codegen)
      id: codegen_pr
      uses: peter-evans/create-pull-request@v7
      with:
        base: master
        commit-message: "feat: update generated Strapi client"
        branch: codegen/${{ github.run_id }}

########################################################################
# 2.2. Codegen - Approve the PR
########################################################################
  codegen-merge:
    needs: codegen-generate
    runs-on: ubuntu-latest
    environment: merge-pr-approval
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0

    - name: Merge codegen PR
      if: ${{ needs.codegen-generate.codegen_pr.outputs.pull-request-number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr merge ${{ needs.codegen-generate.codegen_pr.outputs.pull-request-number }} \
          --merge --delete-branch --admin

########################################################################
# 3. Publish
########################################################################
  publish:
    needs: codegen-merge
    runs-on: ubuntu-latest
    environment: publish-approval
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Package and Push NuGet Package to GitHub Packages
      run: |
        dotnet pack ./src/Poolz.Finance.CSharp.Strapi/Poolz.Finance.CSharp.Strapi.csproj --configuration Release --output nupkg/
        dotnet nuget push nupkg/*.nupkg --source https://nuget.pkg.github.com/The-Poolz/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
